// export const LOGIN_GET_DATA_FROM_SALESFORCE = 'LOGIN_GET_DATA_FROM_SALESFORCE';

// export const AUTH_INIT = 'AUTH_INIT';
// export const AUTH_CLIENT = 'AUTH_CLIENT';
// export const HANDLE_AUTH = 'HANDLE_AUTH';
// export const AUTH_TOKEN = 'AUTH_TOKEN';
// export const AUTH_TOKEN_EXPIRY = 'AUTH_TOKEN_EXPIRY';
// export const AUTH_AUTHENTICATION_STATUS = 'AUTH_AUTHENTICATION_STATUS';
// export const SET_SIGN_IN = 'SIGN_IN';
// export const SET_SIGN_OUT = 'SIGN_OUT';
// export const SET_SF_DETAILS = 'SET_SF_DETAILS';

// export const SET_LOADING_PROFILE = 'SET_LOADING_PROFILE';

// export const SET_LOADING = 'SET_LOADING';
// export const UNSET_LOADING = 'UNSET_LOADING';

// export const ERROR = 'ERROR';

export const LANDING_SELECTED_WALLBOARD_CATEGORY =
  "LANDING_SELECTED_WALLBOARD_CATEGORY";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_USER_TOKEN_INFO = "SET_USER_TOKEN_INFO";
export const SET_USER_INFO = "SET_USER_INFO";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";

export const HANDLE_ADD_COMPONENT_MODAL_SHOW_STATUS =
  "HANDLE_ADD_COMPONENT_MODAL_SHOW_STATUS";
export const HANDLE_NEW_WALLBOARD_TITLE = "HANDLE_NEW_WALLBOARD_TITLE";
export const SET_FILTERED_WALLBOARDS = "SET_FILTERED_WALLBOARDS";
export const SET_WALLBOARDS_LIST = "SET_WALLBOARDS_LIST";
