export const SET_USER_TOKEN_INFO = "SET_USER_TOKEN_INFO";
export const HANDLE_LOGOUT = "HANDLE_LOGOUT";

export const HANDLE_NEW_WALLBOARD_TITLE = "HANDLE_NEW_WALLBOARD_TITLE";
export const LANDING_SELECTED_WALLBOARD_CATEGORY =
  "LANDING_SELECTED_WALLBOARD_CATEGORY";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_FILTERED_WALLBOARDS = "SET_FILTERED_WALLBOARDS";
export const SET_WALLBOARDS_LIST = "SET_WALLBOARDS_LIST";
